export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  LEDGER_NOT_READY: "LEDGER_NOT_READY",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_NOT_RUNNING: "SESSION_NOT_RUNNING",
  QUESTION_NOT_PENDING: "QUESTION_NOT_PENDING",
  DUPLICATE_SUBMISSION: "DUPLICATE_SUBMISSION",
  SNAPSHOT_INVALIDATED: "SNAPSHOT_INVALIDATED",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  RECOVERY_ABORT: "RECOVERY_ABORT"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
