export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  LEDGER_LOCK_HELD: "LEDGER_LOCK_HELD",
  LEDGER_LOCK_EXPIRED: "LEDGER_LOCK_EXPIRED",
  LEDGER_ENTRY_NOT_FOUND: "LEDGER_ENTRY_NOT_FOUND",
  LEDGER_ENTRY_ALREADY_SETTLED: "LEDGER_ENTRY_ALREADY_SETTLED",
  LEDGER_ENTRY_REVOKED: "LEDGER_ENTRY_REVOKED",
  SNAPSHOT_NOT_FOUND: "SNAPSHOT_NOT_FOUND",
  SNAPSHOT_STALE: "SNAPSHOT_STALE",
  SESSION_NOT_ACTIVE: "SESSION_NOT_ACTIVE",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",
  STORAGE_CLEAR_CACHE_FIRST: "STORAGE_CLEAR_CACHE_FIRST"
} as const;
